name: Catalyst
  
dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.8.1
  - name: solmate
    local: node_modules/solmate
    contracts_folder: src

solidity: 
  import_remapping:
    - "@openzeppelin=OpenZeppelin/4.8.1"
    - "solmate=../../node_modules/solmate"

hardhat:
  port: auto

foundry:
  port: auto

test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 8

plugins:
  - name: solidity
  - name: hardhat
  - name: foundry