name: test

on:
  push:
    paths:
      - evm/**

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        working-directory: evm
        id: build

      - name: Run Forge tests
        run: |
          forge test --allow-failure --gas-report --fuzz-seed 10
        working-directory: evm
        id: test
